ports:
  - port: 8000-8999
  
tasks:
  - init: python -m pip install --upgrade pip
    prebuild:  pip install -r requirements.txt
      
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: false
    allLabel: false
    
vscode:
  extensions:
    - ms-python.python
